/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Ultimate Car Racing");
            frame.add(new JLabel(new App().getGreeting()));
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            // Get the default screen device
            GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            if (gd.isFullScreenSupported()) {
                frame.setUndecorated(true); // Remove window decorations
                gd.setFullScreenWindow(frame); // Set the frame to fullscreen
            } else {
                System.err.println("Full screen not supported");
                frame.setSize(300, 100); // Fallback to windowed mode
                frame.setVisible(true);
            }
        });
    }
}
